config/routes.rb
Rails.application.routes.draw do

  root :to => 'site#login'
  
  resources :profile_sessions


  resources :profiles do
    resources :shouts
  end

post 'login' => 'profile_sessions#attempt_login', :as => :login
post 'logout' => 'profile_sessions#logout', :as => :logout
  # # login page and about

  get 'site/login', to: 'site#login'

  get 'site/about', to: 'site#about'

  # for twilio
  # post 'twilio/voice', to: 'twilio#voice'
  # post 'notifications/notify', to: 'notifications#notify'

# Prefix Verb   URI Pattern                                     Controller#Action
#                 root GET    /                                               site#login
#     profile_sessions GET    /profile_sessions(.:format)                     profile_sessions#index
#                      POST   /profile_sessions(.:format)                     profile_sessions#create
#  new_profile_session GET    /profile_sessions/new(.:format)                 profile_sessions#new
# edit_profile_session GET    /profile_sessions/:id/edit(.:format)            profile_sessions#edit
#      profile_session GET    /profile_sessions/:id(.:format)                 profile_sessions#show
#                      PATCH  /profile_sessions/:id(.:format)                 profile_sessions#update
#                      PUT    /profile_sessions/:id(.:format)                 profile_sessions#update
#                      DELETE /profile_sessions/:id(.:format)                 profile_sessions#destroy
#       profile_shouts GET    /profiles/:profile_id/shouts(.:format)          shouts#index
#                      POST   /profiles/:profile_id/shouts(.:format)          shouts#create
#    new_profile_shout GET    /profiles/:profile_id/shouts/new(.:format)      shouts#new
#   edit_profile_shout GET    /profiles/:profile_id/shouts/:id/edit(.:format) shouts#edit
#        profile_shout GET    /profiles/:profile_id/shouts/:id(.:format)      shouts#show
#                      PATCH  /profiles/:profile_id/shouts/:id(.:format)      shouts#update
#                      PUT    /profiles/:profile_id/shouts/:id(.:format)      shouts#update
#                      DELETE /profiles/:profile_id/shouts/:id(.:format)      shouts#destroy
#             profiles GET    /profiles(.:format)                             profiles#index
#                      POST   /profiles(.:format)                             profiles#create
#          new_profile GET    /profiles/new(.:format)                         profiles#new
#         edit_profile GET    /profiles/:id/edit(.:format)                    profiles#edit
#              profile GET    /profiles/:id(.:format)                         profiles#show
#                      PATCH  /profiles/:id(.:format)                         profiles#update
#                      PUT    /profiles/:id(.:format)                         profiles#update
#                      DELETE /profiles/:id(.:format)                         profiles#destroy
#                login GET    /login(.:format)                                profile_sessions#new
#               logout POST   /logout(.:format)                               profile_sessions#destroy
#           site_login GET    /site/login(.:format)                           site#login
#           site_about GET    /site/about(.:format)                           site#about
# notifications_notify POST   /notifications/notify(.:format)                 notifications#notify                notifications#notif                        profiles#destroy

end

app/models/profile.rb
class Profile < ActiveRecord::Base

	has_secure_password

	has_many :shouts, dependent: :destroy
	validates :username, :email, uniqueness: true
	validates :password, length: {minimum: 6}
end

app/controllers/profiles_controller.rb
 class ProfilesController < ApplicationController
  # before_action :find_profile, only: 

  def new
     @profile = Profile.new
  end

  def show
    @profile = Profile.find_by_id(params[:id])
     #render :profile_shouts_path
  end

  def edit
    @profile = Profile.find_by_id(params[:id])
  end

  def create
    @profile = Profile.create profile_params
    puts profile_params
    found_profile_by_username = Profile.where(username: params[:username]).first
    found_profile_by_email = Profile.where(email: params[:email]).first
    if found_profile_by_username or found_profile_by_email
      flash[:error] = "That username or email already exists. Try something different."
      redirect_to new_profile_path
    elsif @profile.save
      redirect_to profile_shouts_path @profile
    else
      redirect_to new_profile_path
      flash[:error] = "Your information is incomplete or you've chosen a username/email that already exists"
    end
    # @profile = Profile.new  profile_params
    # if @profile.save
    #    redirect_to '/profiles/:profile_id/shouts' #:notice => "SHOUT IT OUT!"
    # else 
    #   render 'new'
    # end ### it says the template is missing profiles/create 
  end ##this could be a good resource: http://stackoverflow.com/questions/22671101/what-does-this-mean-missing-template-ruby-rails-4-devise-2
  ##also have an inkling that the user isn't being saved properly, which would cause the 'else' to manifest.

  def update
    @profile = Profile.find_by_id(params[:id])
    if @profile.update_attributes profile_params
      redirect_to profile_shouts_path @profile, notice: "Successfully edited"
    else
      flash[:error] = "Your information is incomplete"
      redirect_to edit_profile_path
    end
  end

  def destroy
    @profile = Profile.find_by_id(params[:id])
    @profile.delete        
    redirect_to root_path
  end

  private
  # def attempt_login 
  #   if params[:username].present? && params[:password].present?
  #     found_profile = Profile.where(username: params[:profile]).first
  #     if found_profile
  #       authorized_profile = found_profile.authenticate(params[:password])
  #     end
  #   end

  def profile_params
    params.require(:profile).permit(:id, :username, :email, :password, :phone_number, :notification)
  end

  def find_profile
    @profile = Profile.find params[:id]
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<h1>Edit Your Profile</h1>
<div class="box">
  <%= form_for @profile do |p| %>
  <div class="label"><%= label_tag(:username)%></div>
  <div class="text"><%= p.text_field :username %></div>
  <div class="label"><%= label_tag(:email)%></div>
  <div class="text"><%= p.text_field :email %></div>
  <div class ="label"><%= p.label :password %></div> 
  <div class="text"><%= p.text_field :password %></div>
  <div class ="label"><%= p.label :phone_number %></div>
  <div class="text"><%= p.text_field :phone_number %></div>
  <div>
    <span id ="note-label"><%= p.label(:notification, "Notify me about new shouts!") %></span>
    <span id ="checkbox"><%= p.check_box(:notification) %></span>
  </div>
</div>
<div class="submit"><%= p.submit "Update Your Profile" %></div>
<% end  %>
<footer>
  <span id="delete"><%= button_to "Delete", profile_path(@profile), :method => :delete  %></span>
  <span id="back"><%= link_to "Back to Shouts!", profile_shouts_path(@profile) %></span>
</footer>

app/views/profiles/index.html.erb
<h1>Profiles#index</h1>
<p>Find me in app/views/profiles/index.html.erb</p>

app/views/profiles/new.html.erb
<h1>Create New Profile </h1>
<div class="box">
  <%= form_for(@profile, url: profiles_path, method: "post") do |f|%>
  <div class ="label"><%= f.label :username  %></div>
  <div class="text"><%= f.text_field :username, placeholder: "Enter a Username", autofocus: true %>
  <div class ="label"><%= f.label :email %></div>
  <div class="text"><%= f.text_field :email, placeholder: "Enter Your Email" %></div>
  <div class ="label"><%= f.label :password %></div>
  <div class="text"><%= f.password_field :password, placeholder: "Make a Password"  %></div>
  <div class ="label"><%= f.label :phone_number %></div>
  <div class="text"><%= f.text_field :phone_number %></div>
  <div>
    <span id ="note-label"><%= f.label(:notification, "Notify me about new shouts!") %></span>
    <span id ="checkbox"><%= f.check_box(:notification) %></span>
  </div>
</div>
<div class="submit"><%= f.submit("Signup", class: "btn btn-primary") %></div>
<% end %>
<footer>
  <div id="signup"><%= link_to "Have an account already? Log in here", site_login_path %></div>
</footer>

app/views/profiles/show.html.erb
<h1>Your Profile</h1>

<%= @profile.username %>
<% @profile.shouts.each do |s| %>
<ul>
  <li><%= link_to "#{s.title}", "/profiles/#{@profile.id}/shouts/#{s.id}"%></li>
</ul>
<% end %>




</body>
<footer>
  <div class="footer">
    <%= link_to "Back to Shouts!", profile_shouts_path(@profile) %>

    <%= link_to "Edit Profile", edit_profile_path(@profile) %>

    <%= link_to "Logout", logout_path, method: :post %> 
  </div>
</footer>